[package]
name = "engine"
version = "0.1.0"
authors = ["NassimBD <nassbd@hotmail.fr>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
